// <auto-generated />
using LinqConsoleApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqConsoleApp.Migrations
{
    [DbContext(typeof(VoorbeeldDBContext))]
    [Migration("20251215081321_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinqConsoleApp.Models.Uitwerking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tries")
                        .HasColumnType("int");

                    b.Property<int?>("VoorbeeldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoorbeeldId");

                    b.ToTable("Uitwerkingen");
                });

            modelBuilder.Entity("LinqConsoleApp.Models.Voorbeeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voorbeelden");
                });

            modelBuilder.Entity("LinqConsoleApp.Models.Uitwerking", b =>
                {
                    b.HasOne("LinqConsoleApp.Models.Voorbeeld", "Voorbeeld")
                        .WithMany("Uitwerkingen")
                        .HasForeignKey("VoorbeeldId");

                    b.Navigation("Voorbeeld");
                });

            modelBuilder.Entity("LinqConsoleApp.Models.Voorbeeld", b =>
                {
                    b.Navigation("Uitwerkingen");
                });
#pragma warning restore 612, 618
        }
    }
}
