// <auto-generated />
using Linq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linq.Migrations
{
    [DbContext(typeof(VoorbeeldDBContext))]
    [Migration("20251215081605_Dataseed")]
    partial class Dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Linq.Models.Uitwerking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tries")
                        .HasColumnType("int");

                    b.Property<int?>("VoorbeeldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoorbeeldId");

                    b.ToTable("Uitwerkingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Owner = "Andrew Wright",
                            Tries = 4,
                            VoorbeeldId = 28
                        },
                        new
                        {
                            Id = 2,
                            Owner = "Isabella Moore",
                            Tries = 16,
                            VoorbeeldId = 65
                        },
                        new
                        {
                            Id = 3,
                            Owner = "Sophia Davis",
                            Tries = 8,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 4,
                            Owner = "Madison Mitchell",
                            Tries = 15,
                            VoorbeeldId = 96
                        },
                        new
                        {
                            Id = 5,
                            Owner = "Luna Roberts",
                            Tries = 9,
                            VoorbeeldId = 90
                        },
                        new
                        {
                            Id = 6,
                            Owner = "Steven Turner",
                            Tries = 3,
                            VoorbeeldId = 59
                        },
                        new
                        {
                            Id = 7,
                            Owner = "Robert Thomas",
                            Tries = 13,
                            VoorbeeldId = 51
                        },
                        new
                        {
                            Id = 8,
                            Owner = "Mark Hill",
                            Tries = 3,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 9,
                            Owner = "Charlotte Martin",
                            Tries = 10,
                            VoorbeeldId = 73
                        },
                        new
                        {
                            Id = 10,
                            Owner = "Robert Thomas",
                            Tries = 11,
                            VoorbeeldId = 79
                        },
                        new
                        {
                            Id = 11,
                            Owner = "Emily Allen",
                            Tries = 4,
                            VoorbeeldId = 94
                        },
                        new
                        {
                            Id = 12,
                            Owner = "Michael Brown",
                            Tries = 2,
                            VoorbeeldId = 22
                        },
                        new
                        {
                            Id = 13,
                            Owner = "Richard Harris",
                            Tries = 4,
                            VoorbeeldId = 30
                        },
                        new
                        {
                            Id = 14,
                            Owner = "David Jackson",
                            Tries = 17,
                            VoorbeeldId = 48
                        },
                        new
                        {
                            Id = 15,
                            Owner = "Joseph Thompson",
                            Tries = 9,
                            VoorbeeldId = 77
                        },
                        new
                        {
                            Id = 16,
                            Owner = "Andrew Wright",
                            Tries = 19,
                            VoorbeeldId = 36
                        },
                        new
                        {
                            Id = 17,
                            Owner = "Brian Carter",
                            Tries = 6,
                            VoorbeeldId = 19
                        },
                        new
                        {
                            Id = 18,
                            Owner = "Luna Roberts",
                            Tries = 12,
                            VoorbeeldId = 62
                        },
                        new
                        {
                            Id = 19,
                            Owner = "Amelia Garcia",
                            Tries = 19,
                            VoorbeeldId = 8
                        },
                        new
                        {
                            Id = 20,
                            Owner = "Charles Rodriguez",
                            Tries = 17,
                            VoorbeeldId = 32
                        },
                        new
                        {
                            Id = 21,
                            Owner = "Kevin Perez",
                            Tries = 17,
                            VoorbeeldId = 90
                        },
                        new
                        {
                            Id = 22,
                            Owner = "John Smith",
                            Tries = 6,
                            VoorbeeldId = 59
                        },
                        new
                        {
                            Id = 23,
                            Owner = "John Smith",
                            Tries = 17,
                            VoorbeeldId = 42
                        },
                        new
                        {
                            Id = 24,
                            Owner = "Sofia Lopez",
                            Tries = 13,
                            VoorbeeldId = 99
                        },
                        new
                        {
                            Id = 25,
                            Owner = "Mia White",
                            Tries = 18,
                            VoorbeeldId = 76
                        },
                        new
                        {
                            Id = 26,
                            Owner = "Emma Johnson",
                            Tries = 7,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 27,
                            Owner = "Emma Johnson",
                            Tries = 14,
                            VoorbeeldId = 53
                        },
                        new
                        {
                            Id = 28,
                            Owner = "Joseph Thompson",
                            Tries = 7,
                            VoorbeeldId = 22
                        },
                        new
                        {
                            Id = 29,
                            Owner = "Christopher Young",
                            Tries = 13,
                            VoorbeeldId = 61
                        },
                        new
                        {
                            Id = 30,
                            Owner = "Richard Harris",
                            Tries = 13,
                            VoorbeeldId = 10
                        },
                        new
                        {
                            Id = 31,
                            Owner = "Olivia Martinez",
                            Tries = 17,
                            VoorbeeldId = 30
                        },
                        new
                        {
                            Id = 32,
                            Owner = "Grace Phillips",
                            Tries = 7,
                            VoorbeeldId = 1
                        },
                        new
                        {
                            Id = 33,
                            Owner = "Emily Allen",
                            Tries = 7,
                            VoorbeeldId = 16
                        },
                        new
                        {
                            Id = 34,
                            Owner = "Ava Taylor",
                            Tries = 13,
                            VoorbeeldId = 11
                        },
                        new
                        {
                            Id = 35,
                            Owner = "Luna Roberts",
                            Tries = 4,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 36,
                            Owner = "Ava Taylor",
                            Tries = 13,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 37,
                            Owner = "Brian Carter",
                            Tries = 7,
                            VoorbeeldId = 62
                        },
                        new
                        {
                            Id = 38,
                            Owner = "Thomas Robinson",
                            Tries = 9,
                            VoorbeeldId = 20
                        },
                        new
                        {
                            Id = 39,
                            Owner = "Ella Adams",
                            Tries = 11,
                            VoorbeeldId = 54
                        },
                        new
                        {
                            Id = 40,
                            Owner = "Andrew Wright",
                            Tries = 8,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 41,
                            Owner = "Steven Turner",
                            Tries = 14,
                            VoorbeeldId = 23
                        },
                        new
                        {
                            Id = 42,
                            Owner = "Richard Harris",
                            Tries = 11,
                            VoorbeeldId = 82
                        },
                        new
                        {
                            Id = 43,
                            Owner = "Sofia Lopez",
                            Tries = 7,
                            VoorbeeldId = 59
                        },
                        new
                        {
                            Id = 44,
                            Owner = "Joshua Green",
                            Tries = 9,
                            VoorbeeldId = 99
                        },
                        new
                        {
                            Id = 45,
                            Owner = "Daniel Lee",
                            Tries = 17,
                            VoorbeeldId = 5
                        },
                        new
                        {
                            Id = 46,
                            Owner = "Thomas Robinson",
                            Tries = 8,
                            VoorbeeldId = 17
                        },
                        new
                        {
                            Id = 47,
                            Owner = "Matthew Hall",
                            Tries = 8,
                            VoorbeeldId = 1
                        },
                        new
                        {
                            Id = 48,
                            Owner = "Steven Turner",
                            Tries = 9,
                            VoorbeeldId = 31
                        },
                        new
                        {
                            Id = 49,
                            Owner = "Evelyn Lewis",
                            Tries = 14,
                            VoorbeeldId = 42
                        },
                        new
                        {
                            Id = 50,
                            Owner = "Sophia Davis",
                            Tries = 4,
                            VoorbeeldId = 80
                        },
                        new
                        {
                            Id = 51,
                            Owner = "Charles Rodriguez",
                            Tries = 18,
                            VoorbeeldId = 94
                        },
                        new
                        {
                            Id = 52,
                            Owner = "Daniel Lee",
                            Tries = 4,
                            VoorbeeldId = 95
                        },
                        new
                        {
                            Id = 53,
                            Owner = "Madison Mitchell",
                            Tries = 13,
                            VoorbeeldId = 64
                        },
                        new
                        {
                            Id = 54,
                            Owner = "Scarlett Nelson",
                            Tries = 10,
                            VoorbeeldId = 33
                        },
                        new
                        {
                            Id = 55,
                            Owner = "Michael Brown",
                            Tries = 3,
                            VoorbeeldId = 91
                        },
                        new
                        {
                            Id = 56,
                            Owner = "Elizabeth King",
                            Tries = 18,
                            VoorbeeldId = 57
                        },
                        new
                        {
                            Id = 57,
                            Owner = "William Anderson",
                            Tries = 8,
                            VoorbeeldId = 14
                        },
                        new
                        {
                            Id = 58,
                            Owner = "Joseph Thompson",
                            Tries = 3,
                            VoorbeeldId = 1
                        },
                        new
                        {
                            Id = 59,
                            Owner = "Andrew Wright",
                            Tries = 1,
                            VoorbeeldId = 24
                        },
                        new
                        {
                            Id = 60,
                            Owner = "Kevin Perez",
                            Tries = 16,
                            VoorbeeldId = 83
                        },
                        new
                        {
                            Id = 61,
                            Owner = "Amelia Garcia",
                            Tries = 12,
                            VoorbeeldId = 13
                        },
                        new
                        {
                            Id = 62,
                            Owner = "Ella Adams",
                            Tries = 6,
                            VoorbeeldId = 55
                        },
                        new
                        {
                            Id = 63,
                            Owner = "Michael Brown",
                            Tries = 1,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 64,
                            Owner = "Sophia Davis",
                            Tries = 11,
                            VoorbeeldId = 79
                        },
                        new
                        {
                            Id = 65,
                            Owner = "Daniel Lee",
                            Tries = 14,
                            VoorbeeldId = 91
                        },
                        new
                        {
                            Id = 66,
                            Owner = "Sofia Lopez",
                            Tries = 17,
                            VoorbeeldId = 36
                        },
                        new
                        {
                            Id = 67,
                            Owner = "Thomas Robinson",
                            Tries = 17,
                            VoorbeeldId = 80
                        },
                        new
                        {
                            Id = 68,
                            Owner = "Scarlett Nelson",
                            Tries = 18,
                            VoorbeeldId = 82
                        },
                        new
                        {
                            Id = 69,
                            Owner = "Andrew Wright",
                            Tries = 2,
                            VoorbeeldId = 80
                        },
                        new
                        {
                            Id = 70,
                            Owner = "Luna Roberts",
                            Tries = 17,
                            VoorbeeldId = 19
                        },
                        new
                        {
                            Id = 71,
                            Owner = "Mark Hill",
                            Tries = 19,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 72,
                            Owner = "Ryan Baker",
                            Tries = 9,
                            VoorbeeldId = 91
                        },
                        new
                        {
                            Id = 73,
                            Owner = "Ava Taylor",
                            Tries = 6,
                            VoorbeeldId = 83
                        },
                        new
                        {
                            Id = 74,
                            Owner = "Joseph Thompson",
                            Tries = 11,
                            VoorbeeldId = 92
                        },
                        new
                        {
                            Id = 75,
                            Owner = "Kevin Perez",
                            Tries = 2,
                            VoorbeeldId = 85
                        },
                        new
                        {
                            Id = 76,
                            Owner = "Charlotte Martin",
                            Tries = 17,
                            VoorbeeldId = 39
                        },
                        new
                        {
                            Id = 77,
                            Owner = "James Wilson",
                            Tries = 19,
                            VoorbeeldId = 14
                        },
                        new
                        {
                            Id = 78,
                            Owner = "Madison Mitchell",
                            Tries = 10,
                            VoorbeeldId = 97
                        },
                        new
                        {
                            Id = 79,
                            Owner = "Emma Johnson",
                            Tries = 11,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 80,
                            Owner = "Richard Harris",
                            Tries = 3,
                            VoorbeeldId = 20
                        },
                        new
                        {
                            Id = 81,
                            Owner = "Avery Scott",
                            Tries = 3,
                            VoorbeeldId = 16
                        },
                        new
                        {
                            Id = 82,
                            Owner = "Charles Rodriguez",
                            Tries = 8,
                            VoorbeeldId = 57
                        },
                        new
                        {
                            Id = 83,
                            Owner = "Grace Phillips",
                            Tries = 14,
                            VoorbeeldId = 28
                        },
                        new
                        {
                            Id = 84,
                            Owner = "Grace Phillips",
                            Tries = 10,
                            VoorbeeldId = 62
                        },
                        new
                        {
                            Id = 85,
                            Owner = "Abigail Walker",
                            Tries = 1,
                            VoorbeeldId = 29
                        },
                        new
                        {
                            Id = 86,
                            Owner = "Madison Mitchell",
                            Tries = 18,
                            VoorbeeldId = 89
                        },
                        new
                        {
                            Id = 87,
                            Owner = "Steven Turner",
                            Tries = 6,
                            VoorbeeldId = 24
                        },
                        new
                        {
                            Id = 88,
                            Owner = "Thomas Robinson",
                            Tries = 16,
                            VoorbeeldId = 88
                        },
                        new
                        {
                            Id = 89,
                            Owner = "Michael Brown",
                            Tries = 16,
                            VoorbeeldId = 46
                        },
                        new
                        {
                            Id = 90,
                            Owner = "Scarlett Nelson",
                            Tries = 15,
                            VoorbeeldId = 89
                        },
                        new
                        {
                            Id = 91,
                            Owner = "David Jackson",
                            Tries = 17,
                            VoorbeeldId = 15
                        },
                        new
                        {
                            Id = 92,
                            Owner = "Christopher Young",
                            Tries = 12,
                            VoorbeeldId = 46
                        },
                        new
                        {
                            Id = 93,
                            Owner = "Joshua Green",
                            Tries = 9,
                            VoorbeeldId = 68
                        },
                        new
                        {
                            Id = 94,
                            Owner = "Mia White",
                            Tries = 7,
                            VoorbeeldId = 15
                        },
                        new
                        {
                            Id = 95,
                            Owner = "James Wilson",
                            Tries = 3,
                            VoorbeeldId = 50
                        },
                        new
                        {
                            Id = 96,
                            Owner = "Daniel Lee",
                            Tries = 7,
                            VoorbeeldId = 47
                        },
                        new
                        {
                            Id = 97,
                            Owner = "Sofia Lopez",
                            Tries = 3,
                            VoorbeeldId = 63
                        },
                        new
                        {
                            Id = 98,
                            Owner = "Ella Adams",
                            Tries = 7,
                            VoorbeeldId = 82
                        },
                        new
                        {
                            Id = 99,
                            Owner = "Steven Turner",
                            Tries = 7,
                            VoorbeeldId = 29
                        },
                        new
                        {
                            Id = 100,
                            Owner = "Mia White",
                            Tries = 8,
                            VoorbeeldId = 56
                        },
                        new
                        {
                            Id = 101,
                            Owner = "James Wilson",
                            Tries = 3,
                            VoorbeeldId = 93
                        },
                        new
                        {
                            Id = 102,
                            Owner = "Amelia Garcia",
                            Tries = 15,
                            VoorbeeldId = 61
                        },
                        new
                        {
                            Id = 103,
                            Owner = "Evelyn Lewis",
                            Tries = 18,
                            VoorbeeldId = 44
                        },
                        new
                        {
                            Id = 104,
                            Owner = "Ryan Baker",
                            Tries = 3,
                            VoorbeeldId = 48
                        },
                        new
                        {
                            Id = 105,
                            Owner = "Robert Thomas",
                            Tries = 13,
                            VoorbeeldId = 95
                        },
                        new
                        {
                            Id = 106,
                            Owner = "Sophia Davis",
                            Tries = 6,
                            VoorbeeldId = 73
                        },
                        new
                        {
                            Id = 107,
                            Owner = "Amelia Garcia",
                            Tries = 11,
                            VoorbeeldId = 48
                        },
                        new
                        {
                            Id = 108,
                            Owner = "Grace Phillips",
                            Tries = 3,
                            VoorbeeldId = 63
                        },
                        new
                        {
                            Id = 109,
                            Owner = "David Jackson",
                            Tries = 10,
                            VoorbeeldId = 53
                        },
                        new
                        {
                            Id = 110,
                            Owner = "Charlotte Martin",
                            Tries = 13,
                            VoorbeeldId = 28
                        },
                        new
                        {
                            Id = 111,
                            Owner = "William Anderson",
                            Tries = 10,
                            VoorbeeldId = 5
                        },
                        new
                        {
                            Id = 112,
                            Owner = "James Wilson",
                            Tries = 4,
                            VoorbeeldId = 23
                        },
                        new
                        {
                            Id = 113,
                            Owner = "Robert Thomas",
                            Tries = 14,
                            VoorbeeldId = 37
                        },
                        new
                        {
                            Id = 114,
                            Owner = "Madison Mitchell",
                            Tries = 1,
                            VoorbeeldId = 45
                        },
                        new
                        {
                            Id = 115,
                            Owner = "Emma Johnson",
                            Tries = 17,
                            VoorbeeldId = 5
                        },
                        new
                        {
                            Id = 116,
                            Owner = "William Anderson",
                            Tries = 11,
                            VoorbeeldId = 68
                        },
                        new
                        {
                            Id = 117,
                            Owner = "Brian Carter",
                            Tries = 17,
                            VoorbeeldId = 5
                        },
                        new
                        {
                            Id = 118,
                            Owner = "Matthew Hall",
                            Tries = 18,
                            VoorbeeldId = 87
                        },
                        new
                        {
                            Id = 119,
                            Owner = "Sophia Davis",
                            Tries = 3,
                            VoorbeeldId = 99
                        },
                        new
                        {
                            Id = 120,
                            Owner = "Mia White",
                            Tries = 3,
                            VoorbeeldId = 27
                        },
                        new
                        {
                            Id = 121,
                            Owner = "Sophia Davis",
                            Tries = 3,
                            VoorbeeldId = 25
                        },
                        new
                        {
                            Id = 122,
                            Owner = "William Anderson",
                            Tries = 13,
                            VoorbeeldId = 63
                        },
                        new
                        {
                            Id = 123,
                            Owner = "Harper Clark",
                            Tries = 2,
                            VoorbeeldId = 51
                        },
                        new
                        {
                            Id = 124,
                            Owner = "Mark Hill",
                            Tries = 17,
                            VoorbeeldId = 57
                        },
                        new
                        {
                            Id = 125,
                            Owner = "Joseph Thompson",
                            Tries = 10,
                            VoorbeeldId = 51
                        },
                        new
                        {
                            Id = 126,
                            Owner = "Emma Johnson",
                            Tries = 18,
                            VoorbeeldId = 30
                        },
                        new
                        {
                            Id = 127,
                            Owner = "Emily Allen",
                            Tries = 3,
                            VoorbeeldId = 91
                        },
                        new
                        {
                            Id = 128,
                            Owner = "Brian Carter",
                            Tries = 9,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 129,
                            Owner = "Isabella Moore",
                            Tries = 12,
                            VoorbeeldId = 59
                        },
                        new
                        {
                            Id = 130,
                            Owner = "Ava Taylor",
                            Tries = 1,
                            VoorbeeldId = 5
                        },
                        new
                        {
                            Id = 131,
                            Owner = "Isabella Moore",
                            Tries = 18,
                            VoorbeeldId = 61
                        },
                        new
                        {
                            Id = 132,
                            Owner = "Sophia Davis",
                            Tries = 16,
                            VoorbeeldId = 89
                        },
                        new
                        {
                            Id = 133,
                            Owner = "Ava Taylor",
                            Tries = 17,
                            VoorbeeldId = 22
                        },
                        new
                        {
                            Id = 134,
                            Owner = "Thomas Robinson",
                            Tries = 14,
                            VoorbeeldId = 50
                        },
                        new
                        {
                            Id = 135,
                            Owner = "William Anderson",
                            Tries = 3,
                            VoorbeeldId = 98
                        },
                        new
                        {
                            Id = 136,
                            Owner = "Evelyn Lewis",
                            Tries = 4,
                            VoorbeeldId = 42
                        },
                        new
                        {
                            Id = 137,
                            Owner = "Joseph Thompson",
                            Tries = 1,
                            VoorbeeldId = 18
                        },
                        new
                        {
                            Id = 138,
                            Owner = "Sofia Lopez",
                            Tries = 14,
                            VoorbeeldId = 2
                        },
                        new
                        {
                            Id = 139,
                            Owner = "Joseph Thompson",
                            Tries = 5,
                            VoorbeeldId = 70
                        },
                        new
                        {
                            Id = 140,
                            Owner = "Harper Clark",
                            Tries = 18,
                            VoorbeeldId = 4
                        },
                        new
                        {
                            Id = 141,
                            Owner = "Emma Johnson",
                            Tries = 5,
                            VoorbeeldId = 4
                        },
                        new
                        {
                            Id = 142,
                            Owner = "Charles Rodriguez",
                            Tries = 10,
                            VoorbeeldId = 97
                        },
                        new
                        {
                            Id = 143,
                            Owner = "Steven Turner",
                            Tries = 5,
                            VoorbeeldId = 68
                        },
                        new
                        {
                            Id = 144,
                            Owner = "Christopher Young",
                            Tries = 17,
                            VoorbeeldId = 7
                        },
                        new
                        {
                            Id = 145,
                            Owner = "Sophia Davis",
                            Tries = 4,
                            VoorbeeldId = 39
                        },
                        new
                        {
                            Id = 146,
                            Owner = "Thomas Robinson",
                            Tries = 14,
                            VoorbeeldId = 32
                        },
                        new
                        {
                            Id = 147,
                            Owner = "Ryan Baker",
                            Tries = 15,
                            VoorbeeldId = 41
                        },
                        new
                        {
                            Id = 148,
                            Owner = "William Anderson",
                            Tries = 16,
                            VoorbeeldId = 1
                        },
                        new
                        {
                            Id = 149,
                            Owner = "Brian Carter",
                            Tries = 11,
                            VoorbeeldId = 21
                        },
                        new
                        {
                            Id = 150,
                            Owner = "Emily Allen",
                            Tries = 14,
                            VoorbeeldId = 59
                        },
                        new
                        {
                            Id = 151,
                            Owner = "Ava Taylor",
                            Tries = 15,
                            VoorbeeldId = 97
                        },
                        new
                        {
                            Id = 152,
                            Owner = "William Anderson",
                            Tries = 8,
                            VoorbeeldId = 48
                        },
                        new
                        {
                            Id = 153,
                            Owner = "Charles Rodriguez",
                            Tries = 14,
                            VoorbeeldId = 66
                        },
                        new
                        {
                            Id = 154,
                            Owner = "John Smith",
                            Tries = 10,
                            VoorbeeldId = 95
                        },
                        new
                        {
                            Id = 155,
                            Owner = "Avery Scott",
                            Tries = 15,
                            VoorbeeldId = 20
                        },
                        new
                        {
                            Id = 156,
                            Owner = "James Wilson",
                            Tries = 12,
                            VoorbeeldId = 54
                        },
                        new
                        {
                            Id = 157,
                            Owner = "Elizabeth King",
                            Tries = 19,
                            VoorbeeldId = 54
                        },
                        new
                        {
                            Id = 158,
                            Owner = "Joseph Thompson",
                            Tries = 12,
                            VoorbeeldId = 17
                        },
                        new
                        {
                            Id = 159,
                            Owner = "Elizabeth King",
                            Tries = 17,
                            VoorbeeldId = 44
                        },
                        new
                        {
                            Id = 160,
                            Owner = "Emma Johnson",
                            Tries = 12,
                            VoorbeeldId = 96
                        },
                        new
                        {
                            Id = 161,
                            Owner = "Joshua Green",
                            Tries = 8,
                            VoorbeeldId = 54
                        },
                        new
                        {
                            Id = 162,
                            Owner = "Sophia Davis",
                            Tries = 9,
                            VoorbeeldId = 10
                        },
                        new
                        {
                            Id = 163,
                            Owner = "James Wilson",
                            Tries = 18,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 164,
                            Owner = "Kevin Perez",
                            Tries = 19,
                            VoorbeeldId = 99
                        },
                        new
                        {
                            Id = 165,
                            Owner = "Andrew Wright",
                            Tries = 16,
                            VoorbeeldId = 25
                        },
                        new
                        {
                            Id = 166,
                            Owner = "Charles Rodriguez",
                            Tries = 9,
                            VoorbeeldId = 8
                        },
                        new
                        {
                            Id = 167,
                            Owner = "Ryan Baker",
                            Tries = 15,
                            VoorbeeldId = 92
                        },
                        new
                        {
                            Id = 168,
                            Owner = "Andrew Wright",
                            Tries = 19,
                            VoorbeeldId = 78
                        },
                        new
                        {
                            Id = 169,
                            Owner = "Michael Brown",
                            Tries = 16,
                            VoorbeeldId = 12
                        },
                        new
                        {
                            Id = 170,
                            Owner = "Ella Adams",
                            Tries = 11,
                            VoorbeeldId = 49
                        },
                        new
                        {
                            Id = 171,
                            Owner = "Emma Johnson",
                            Tries = 9,
                            VoorbeeldId = 12
                        },
                        new
                        {
                            Id = 172,
                            Owner = "Mark Hill",
                            Tries = 5,
                            VoorbeeldId = 14
                        },
                        new
                        {
                            Id = 173,
                            Owner = "Thomas Robinson",
                            Tries = 13,
                            VoorbeeldId = 32
                        },
                        new
                        {
                            Id = 174,
                            Owner = "Sophia Davis",
                            Tries = 1,
                            VoorbeeldId = 72
                        },
                        new
                        {
                            Id = 175,
                            Owner = "Avery Scott",
                            Tries = 14,
                            VoorbeeldId = 100
                        },
                        new
                        {
                            Id = 176,
                            Owner = "Abigail Walker",
                            Tries = 14,
                            VoorbeeldId = 81
                        },
                        new
                        {
                            Id = 177,
                            Owner = "Luna Roberts",
                            Tries = 4,
                            VoorbeeldId = 46
                        },
                        new
                        {
                            Id = 178,
                            Owner = "Joseph Thompson",
                            Tries = 5,
                            VoorbeeldId = 84
                        },
                        new
                        {
                            Id = 179,
                            Owner = "Emma Johnson",
                            Tries = 2,
                            VoorbeeldId = 42
                        },
                        new
                        {
                            Id = 180,
                            Owner = "Joshua Green",
                            Tries = 1,
                            VoorbeeldId = 61
                        },
                        new
                        {
                            Id = 181,
                            Owner = "Grace Phillips",
                            Tries = 6,
                            VoorbeeldId = 37
                        },
                        new
                        {
                            Id = 182,
                            Owner = "Richard Harris",
                            Tries = 17,
                            VoorbeeldId = 53
                        },
                        new
                        {
                            Id = 183,
                            Owner = "Madison Mitchell",
                            Tries = 19,
                            VoorbeeldId = 57
                        },
                        new
                        {
                            Id = 184,
                            Owner = "James Wilson",
                            Tries = 1,
                            VoorbeeldId = 78
                        },
                        new
                        {
                            Id = 185,
                            Owner = "Joshua Green",
                            Tries = 14,
                            VoorbeeldId = 75
                        },
                        new
                        {
                            Id = 186,
                            Owner = "Robert Thomas",
                            Tries = 18,
                            VoorbeeldId = 24
                        },
                        new
                        {
                            Id = 187,
                            Owner = "Ella Adams",
                            Tries = 10,
                            VoorbeeldId = 12
                        },
                        new
                        {
                            Id = 188,
                            Owner = "Richard Harris",
                            Tries = 17,
                            VoorbeeldId = 37
                        },
                        new
                        {
                            Id = 189,
                            Owner = "Emma Johnson",
                            Tries = 13,
                            VoorbeeldId = 22
                        },
                        new
                        {
                            Id = 190,
                            Owner = "Mia White",
                            Tries = 13,
                            VoorbeeldId = 16
                        },
                        new
                        {
                            Id = 191,
                            Owner = "Mark Hill",
                            Tries = 13,
                            VoorbeeldId = 62
                        },
                        new
                        {
                            Id = 192,
                            Owner = "Mark Hill",
                            Tries = 3,
                            VoorbeeldId = 70
                        },
                        new
                        {
                            Id = 193,
                            Owner = "Joseph Thompson",
                            Tries = 9,
                            VoorbeeldId = 85
                        },
                        new
                        {
                            Id = 194,
                            Owner = "Charles Rodriguez",
                            Tries = 13,
                            VoorbeeldId = 75
                        },
                        new
                        {
                            Id = 195,
                            Owner = "Isabella Moore",
                            Tries = 16,
                            VoorbeeldId = 14
                        },
                        new
                        {
                            Id = 196,
                            Owner = "Sofia Lopez",
                            Tries = 12,
                            VoorbeeldId = 51
                        },
                        new
                        {
                            Id = 197,
                            Owner = "Sophia Davis",
                            Tries = 16,
                            VoorbeeldId = 16
                        },
                        new
                        {
                            Id = 198,
                            Owner = "Ava Taylor",
                            Tries = 19,
                            VoorbeeldId = 53
                        },
                        new
                        {
                            Id = 199,
                            Owner = "Evelyn Lewis",
                            Tries = 13,
                            VoorbeeldId = 45
                        },
                        new
                        {
                            Id = 200,
                            Owner = "Grace Phillips",
                            Tries = 6,
                            VoorbeeldId = 20
                        });
                });

            modelBuilder.Entity("Linq.Models.Voorbeeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voorbeelden");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 67,
                            Description = "Transform a collection of numbers using Select operator",
                            Name = "LINQ Select Query",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Count = 13,
                            Description = "Filter a list of products based on price criteria",
                            Name = "LINQ Where Filter",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            Count = 17,
                            Description = "Sort employees by their salary in ascending order",
                            Name = "LINQ OrderBy Sorting",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Count = 72,
                            Description = "Group customers by their country of residence",
                            Name = "LINQ GroupBy Operation",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            Count = 18,
                            Description = "Combine orders with customer information using Join",
                            Name = "LINQ Join Tables",
                            Role = 3
                        },
                        new
                        {
                            Id = 6,
                            Count = 24,
                            Description = "Calculate the total revenue from all sales",
                            Name = "LINQ Aggregate Sum",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            Count = 51,
                            Description = "Check if any student passed the exam",
                            Name = "LINQ Any Condition",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            Count = 38,
                            Description = "Verify that all products are in stock",
                            Name = "LINQ All Validation",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            Count = 52,
                            Description = "Get the first order placed by a customer",
                            Name = "LINQ First Element",
                            Role = 0
                        },
                        new
                        {
                            Id = 10,
                            Count = 81,
                            Description = "Implement pagination for a product list",
                            Name = "LINQ Skip and Take",
                            Role = 2
                        },
                        new
                        {
                            Id = 11,
                            Count = 40,
                            Description = "Insert a new customer into the database",
                            Name = "Entity Framework Add",
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            Count = 9,
                            Description = "Modify existing product information",
                            Name = "Entity Framework Update",
                            Role = 3
                        },
                        new
                        {
                            Id = 13,
                            Count = 81,
                            Description = "Remove an obsolete record from inventory",
                            Name = "Entity Framework Delete",
                            Role = 2
                        },
                        new
                        {
                            Id = 14,
                            Count = 5,
                            Description = "Load related entities using eager loading",
                            Name = "Entity Framework Include",
                            Role = 3
                        },
                        new
                        {
                            Id = 15,
                            Count = 15,
                            Description = "Execute asynchronous database queries efficiently",
                            Name = "Async Query Pattern",
                            Role = 4
                        },
                        new
                        {
                            Id = 16,
                            Count = 69,
                            Description = "Filter data using multiple AND/OR conditions",
                            Name = "Complex Where Clause",
                            Role = 2
                        },
                        new
                        {
                            Id = 17,
                            Count = 19,
                            Description = "Flatten nested collections into a single sequence",
                            Name = "LINQ SelectMany Flatten",
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            Count = 31,
                            Description = "Remove duplicate entries from a result set",
                            Name = "LINQ Distinct Values",
                            Role = 2
                        },
                        new
                        {
                            Id = 19,
                            Count = 82,
                            Description = "Count the number of active users in the system",
                            Name = "LINQ Count Records",
                            Role = 0
                        },
                        new
                        {
                            Id = 20,
                            Count = 54,
                            Description = "Calculate average product rating from reviews",
                            Name = "LINQ Average Calculation",
                            Role = 4
                        },
                        new
                        {
                            Id = 21,
                            Count = 75,
                            Description = "Find the highest and lowest temperatures recorded",
                            Name = "LINQ Max and Min",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            Count = 15,
                            Description = "Search for specific items in a collection",
                            Name = "LINQ Contains Search",
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            Count = 6,
                            Description = "Find elements that exist in one set but not another",
                            Name = "LINQ Except Difference",
                            Role = 3
                        },
                        new
                        {
                            Id = 24,
                            Count = 63,
                            Description = "Merge two collections removing duplicates",
                            Name = "LINQ Union Combine",
                            Role = 0
                        },
                        new
                        {
                            Id = 25,
                            Count = 25,
                            Description = "Find common elements between two datasets",
                            Name = "LINQ Intersect Common",
                            Role = 3
                        },
                        new
                        {
                            Id = 26,
                            Count = 29,
                            Description = "Apply secondary sorting criteria to results",
                            Name = "LINQ ThenBy Sorting",
                            Role = 3
                        },
                        new
                        {
                            Id = 27,
                            Count = 15,
                            Description = "Reverse the order of elements in a sequence",
                            Name = "LINQ Reverse Order",
                            Role = 0
                        },
                        new
                        {
                            Id = 28,
                            Count = 60,
                            Description = "Retrieve exactly one record matching criteria",
                            Name = "LINQ Single Record",
                            Role = 2
                        },
                        new
                        {
                            Id = 29,
                            Count = 6,
                            Description = "Handle empty result sets with default values",
                            Name = "LINQ DefaultIfEmpty",
                            Role = 2
                        },
                        new
                        {
                            Id = 30,
                            Count = 70,
                            Description = "Filter elements by their specific type",
                            Name = "LINQ OfType Filtering",
                            Role = 3
                        },
                        new
                        {
                            Id = 31,
                            Count = 22,
                            Description = "Convert collection elements to a specific type",
                            Name = "LINQ Cast Conversion",
                            Role = 0
                        },
                        new
                        {
                            Id = 32,
                            Count = 37,
                            Description = "Combine two sequences element by element",
                            Name = "LINQ Zip Combine",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            Count = 7,
                            Description = "Generate a sequence of numbers within a range",
                            Name = "LINQ Range Generation",
                            Role = 3
                        },
                        new
                        {
                            Id = 34,
                            Count = 8,
                            Description = "Create a sequence with repeated values",
                            Name = "LINQ Repeat Elements",
                            Role = 2
                        },
                        new
                        {
                            Id = 35,
                            Count = 2,
                            Description = "Create an empty enumerable of a type",
                            Name = "LINQ Empty Collection",
                            Role = 3
                        },
                        new
                        {
                            Id = 36,
                            Count = 44,
                            Description = "Access related entities through navigation",
                            Name = "Navigation Properties",
                            Role = 2
                        },
                        new
                        {
                            Id = 37,
                            Count = 50,
                            Description = "Configure lazy loading for related data",
                            Name = "Lazy Loading Setup",
                            Role = 0
                        },
                        new
                        {
                            Id = 38,
                            Count = 83,
                            Description = "Track entity state changes in DbContext",
                            Name = "Change Tracking",
                            Role = 0
                        },
                        new
                        {
                            Id = 39,
                            Count = 1,
                            Description = "Manage database transactions with SaveChanges",
                            Name = "Transaction Handling",
                            Role = 0
                        },
                        new
                        {
                            Id = 40,
                            Count = 65,
                            Description = "Insert multiple records efficiently",
                            Name = "Bulk Insert Operation",
                            Role = 0
                        },
                        new
                        {
                            Id = 41,
                            Count = 91,
                            Description = "Optimize LINQ queries for better performance",
                            Name = "Query Performance",
                            Role = 4
                        },
                        new
                        {
                            Id = 42,
                            Count = 46,
                            Description = "Utilize database indexes in queries",
                            Name = "Index Usage",
                            Role = 1
                        },
                        new
                        {
                            Id = 43,
                            Count = 62,
                            Description = "Pre-compile frequently used queries",
                            Name = "Compiled Queries",
                            Role = 0
                        },
                        new
                        {
                            Id = 44,
                            Count = 37,
                            Description = "Project query results to DTOs or ViewModels",
                            Name = "Projection Mapping",
                            Role = 0
                        },
                        new
                        {
                            Id = 45,
                            Count = 44,
                            Description = "Perform string filtering and manipulation",
                            Name = "String Operations",
                            Role = 3
                        },
                        new
                        {
                            Id = 46,
                            Count = 53,
                            Description = "Filter records based on date ranges",
                            Name = "Date Filtering",
                            Role = 2
                        },
                        new
                        {
                            Id = 47,
                            Count = 30,
                            Description = "Handle nullable properties in LINQ queries",
                            Name = "Null Handling",
                            Role = 4
                        },
                        new
                        {
                            Id = 48,
                            Count = 59,
                            Description = "Implement conditional expressions in queries",
                            Name = "Conditional Logic",
                            Role = 3
                        },
                        new
                        {
                            Id = 49,
                            Count = 2,
                            Description = "Use subqueries within main queries",
                            Name = "Subquery Pattern",
                            Role = 4
                        },
                        new
                        {
                            Id = 50,
                            Count = 95,
                            Description = "Perform left outer joins between tables",
                            Name = "Left Join Implementation",
                            Role = 1
                        },
                        new
                        {
                            Id = 51,
                            Count = 71,
                            Description = "Combine grouping with join operations",
                            Name = "Group Join Pattern",
                            Role = 0
                        },
                        new
                        {
                            Id = 52,
                            Count = 11,
                            Description = "Introduce range variables in query syntax",
                            Name = "Let Clause Usage",
                            Role = 2
                        },
                        new
                        {
                            Id = 53,
                            Count = 33,
                            Description = "Continue queries after grouping or joining",
                            Name = "Into Continuation",
                            Role = 3
                        },
                        new
                        {
                            Id = 54,
                            Count = 15,
                            Description = "Compare query and method syntax approaches",
                            Name = "Query Syntax vs Method",
                            Role = 0
                        },
                        new
                        {
                            Id = 55,
                            Count = 22,
                            Description = "Understand lazy evaluation of LINQ queries",
                            Name = "Deferred Execution",
                            Role = 2
                        },
                        new
                        {
                            Id = 56,
                            Count = 51,
                            Description = "Force immediate query execution with ToList",
                            Name = "Immediate Execution",
                            Role = 4
                        },
                        new
                        {
                            Id = 57,
                            Count = 76,
                            Description = "Execute read-only queries without tracking",
                            Name = "AsNoTracking Query",
                            Role = 3
                        },
                        new
                        {
                            Id = 58,
                            Count = 71,
                            Description = "Retrieve entity by its primary key value",
                            Name = "Find by Primary Key",
                            Role = 1
                        },
                        new
                        {
                            Id = 59,
                            Count = 55,
                            Description = "Query the local DbContext cache",
                            Name = "Local Cache Access",
                            Role = 4
                        },
                        new
                        {
                            Id = 60,
                            Count = 65,
                            Description = "Attach existing entity to context for updates",
                            Name = "Attach Entity",
                            Role = 0
                        },
                        new
                        {
                            Id = 61,
                            Count = 35,
                            Description = "Access entity metadata and state information",
                            Name = "Entry Metadata",
                            Role = 4
                        },
                        new
                        {
                            Id = 62,
                            Count = 3,
                            Description = "Map complex types in entity models",
                            Name = "Complex Type Mapping",
                            Role = 1
                        },
                        new
                        {
                            Id = 63,
                            Count = 27,
                            Description = "Convert property values during persistence",
                            Name = "Value Conversion",
                            Role = 0
                        },
                        new
                        {
                            Id = 64,
                            Count = 22,
                            Description = "Use properties not in entity class definition",
                            Name = "Shadow Properties",
                            Role = 2
                        },
                        new
                        {
                            Id = 65,
                            Count = 42,
                            Description = "Configure backing fields for properties",
                            Name = "Backing Fields",
                            Role = 0
                        },
                        new
                        {
                            Id = 66,
                            Count = 99,
                            Description = "Handle concurrent updates with tokens",
                            Name = "Concurrency Tokens",
                            Role = 0
                        },
                        new
                        {
                            Id = 67,
                            Count = 11,
                            Description = "Implement logical deletion of records",
                            Name = "Soft Delete Pattern",
                            Role = 1
                        },
                        new
                        {
                            Id = 68,
                            Count = 33,
                            Description = "Apply automatic filters to all queries",
                            Name = "Global Query Filters",
                            Role = 3
                        },
                        new
                        {
                            Id = 69,
                            Count = 82,
                            Description = "Map multiple entities to single table",
                            Name = "Table Splitting",
                            Role = 0
                        },
                        new
                        {
                            Id = 70,
                            Count = 5,
                            Description = "Map single entity across multiple tables",
                            Name = "Entity Splitting",
                            Role = 4
                        },
                        new
                        {
                            Id = 71,
                            Count = 89,
                            Description = "Table-per-hierarchy inheritance mapping",
                            Name = "Inheritance TPH",
                            Role = 1
                        },
                        new
                        {
                            Id = 72,
                            Count = 92,
                            Description = "Table-per-type inheritance strategy",
                            Name = "Inheritance TPT",
                            Role = 4
                        },
                        new
                        {
                            Id = 73,
                            Count = 28,
                            Description = "Table-per-concrete-class mapping",
                            Name = "Inheritance TPC",
                            Role = 2
                        },
                        new
                        {
                            Id = 74,
                            Count = 63,
                            Description = "Configure many-to-many relationships",
                            Name = "Many-to-Many Relation",
                            Role = 3
                        },
                        new
                        {
                            Id = 75,
                            Count = 20,
                            Description = "Set up one-to-one entity relationships",
                            Name = "One-to-One Relation",
                            Role = 1
                        },
                        new
                        {
                            Id = 76,
                            Count = 19,
                            Description = "Configure one-to-many associations",
                            Name = "One-to-Many Relation",
                            Role = 0
                        },
                        new
                        {
                            Id = 77,
                            Count = 23,
                            Description = "Create self-referencing entity relationships",
                            Name = "Self Referencing",
                            Role = 4
                        },
                        new
                        {
                            Id = 78,
                            Count = 98,
                            Description = "Configure cascading delete behavior",
                            Name = "Cascade Delete",
                            Role = 3
                        },
                        new
                        {
                            Id = 79,
                            Count = 14,
                            Description = "Make navigation properties required",
                            Name = "Required Navigation",
                            Role = 4
                        },
                        new
                        {
                            Id = 80,
                            Count = 19,
                            Description = "Configure optional relationships",
                            Name = "Optional Navigation",
                            Role = 1
                        },
                        new
                        {
                            Id = 81,
                            Count = 56,
                            Description = "Define composite keys for entities",
                            Name = "Composite Primary Key",
                            Role = 2
                        },
                        new
                        {
                            Id = 82,
                            Count = 71,
                            Description = "Configure alternate unique keys",
                            Name = "Alternate Keys",
                            Role = 0
                        },
                        new
                        {
                            Id = 83,
                            Count = 60,
                            Description = "Create database indexes for performance",
                            Name = "Index Configuration",
                            Role = 1
                        },
                        new
                        {
                            Id = 84,
                            Count = 88,
                            Description = "Add unique constraints to properties",
                            Name = "Unique Constraints",
                            Role = 2
                        },
                        new
                        {
                            Id = 85,
                            Count = 35,
                            Description = "Define check constraints on tables",
                            Name = "Check Constraints",
                            Role = 4
                        },
                        new
                        {
                            Id = 86,
                            Count = 46,
                            Description = "Set default values for properties",
                            Name = "Default Values",
                            Role = 2
                        },
                        new
                        {
                            Id = 87,
                            Count = 94,
                            Description = "Configure computed column expressions",
                            Name = "Computed Columns",
                            Role = 4
                        },
                        new
                        {
                            Id = 88,
                            Count = 13,
                            Description = "Execute stored procedures from EF Core",
                            Name = "Stored Procedure Call",
                            Role = 0
                        },
                        new
                        {
                            Id = 89,
                            Count = 1,
                            Description = "Execute raw SQL queries safely",
                            Name = "Raw SQL Query",
                            Role = 0
                        },
                        new
                        {
                            Id = 90,
                            Count = 94,
                            Description = "Use interpolated strings in SQL queries",
                            Name = "SQL Interpolation",
                            Role = 3
                        },
                        new
                        {
                            Id = 91,
                            Count = 40,
                            Description = "Call database functions in LINQ",
                            Name = "Database Functions",
                            Role = 2
                        },
                        new
                        {
                            Id = 92,
                            Count = 40,
                            Description = "Map and use user-defined functions",
                            Name = "User-Defined Functions",
                            Role = 0
                        },
                        new
                        {
                            Id = 93,
                            Count = 91,
                            Description = "Map entities to database views",
                            Name = "View Mapping",
                            Role = 4
                        },
                        new
                        {
                            Id = 94,
                            Count = 89,
                            Description = "Work with SQL Server temporal tables",
                            Name = "Temporal Tables",
                            Role = 0
                        },
                        new
                        {
                            Id = 95,
                            Count = 34,
                            Description = "Configure owned entity types",
                            Name = "Owned Entity Types",
                            Role = 2
                        },
                        new
                        {
                            Id = 96,
                            Count = 61,
                            Description = "Define entities without primary keys",
                            Name = "Keyless Entity Types",
                            Role = 4
                        },
                        new
                        {
                            Id = 97,
                            Count = 82,
                            Description = "Add tags to queries for logging",
                            Name = "Query Tags",
                            Role = 3
                        },
                        new
                        {
                            Id = 98,
                            Count = 28,
                            Description = "Split complex queries for performance",
                            Name = "Split Queries",
                            Role = 1
                        },
                        new
                        {
                            Id = 99,
                            Count = 53,
                            Description = "Perform batch update operations",
                            Name = "Batch Updates",
                            Role = 4
                        },
                        new
                        {
                            Id = 100,
                            Count = 25,
                            Description = "Execute batch delete operations",
                            Name = "Batch Deletes",
                            Role = 4
                        });
                });

            modelBuilder.Entity("Linq.Models.Uitwerking", b =>
                {
                    b.HasOne("Linq.Models.Voorbeeld", "Voorbeeld")
                        .WithMany("Uitwerkingen")
                        .HasForeignKey("VoorbeeldId");

                    b.Navigation("Voorbeeld");
                });

            modelBuilder.Entity("Linq.Models.Voorbeeld", b =>
                {
                    b.Navigation("Uitwerkingen");
                });
#pragma warning restore 612, 618
        }
    }
}
